### ISSUE TITLE
File does not exist error after file deletion

### ISSUE THREAD

**Issue by 3ru** [3ru/gpt-translate#22]
https://github.com/3ru/gpt-translate/issues/20#issuecomment-1634988106

- [ ] Investigation not fired when creating a file with the same name

**Comment by 3ru** [comment]
If a non-existent file is specified, it is appropriate to raise an error.

To avoid specifying a non-existent file in a commit-triggered workflow, we offer the following input file specification as an example.

```yml
- name: get changed files name
  id: changed_files
  run: |
    echo "files=$(git diff --name-only HEAD^ HEAD | grep '\.md$' | while read file; do [ -f "$file" ] && echo "$file"; done | tr '\n' ' ')" >> $GITHUB_OUTPUT

- name: Run GPT Translate
  uses: 3ru/gpt-translate@master
  with:
    apikey: ${{ secrets.OPENAI_API_KEY }}
    model: "gpt-4"
    inputFiles: ${{ steps.changed_files.outputs.files }}
    outputFiles: "JP/**/*.md"
    languages: "Japanese"
```

In the `get changed files name' section, md files with differences are extracted, and only those files that currently exist are specified for translation.
