### ISSUE TITLE
GPT 4

### ISSUE THREAD

**Issue by makeitr3al** [3ru/gpt-translate#27]
Hi @3ru I know have access to the API from GPT 4.
Is it possible to use this engine then?

**Comment by 3ru** [comment]
I will have time tomorrow to address your issue and this if possible.

**Comment by 3ru** [comment]
@makeitr3al 

With https://github.com/3ru/gpt-translate/releases/tag/v1.1.5, it is now possible to specify a model 🎉 
```yml
  with:
    apikey: ${{ secrets.OPENAI_API_KEY }}
    model: "gpt-4"
```
