### ISSUE TITLE
Some image paths are missing.

### ISSUE THREAD

**Issue by zhgchgli0718** [3ru/gpt-translate#85]
### Link to the environment that reproduces this issue or a replay of the bug

https://github.com/ZhgChgLi/zhgchgli.github.io/pull/15

### To Reproduce

Hi, this tool is awesome! However, I am facing some issues with image paths in my Markdown file.

The original Markdown file: [link](https://github.com/ZhgChgLi/zhgchgli.github.io/blob/main/_posts/zh-tw/zmediumtomarkdown/2024-08-13-755509180ca8.md)
After using GPT-Translate, the translated file: [link](https://github.com/ZhgChgLi/zhgchgli.github.io/blob/96e685e96e95f3a8ade1c1a042d523f3ca4da1a3/_posts/en/zmediumtomarkdown/2024-08-13-755509180ca8.md)

You can see that some image paths are incorrect.
The paths have been modified to the wrong format, such as `![Image](path/to/image.png)`.

Thanks.

### Current vs. Expected behavior

Current: `![Image](path/to/image.png)`
Expected behavior: the original image path like `![image title](/assets/mycat.png)`

### Provide environment information

```yml
# .github/workflows/gpt-translate.yml
name: GPT Translate

on:
  issue_comment:
    types: [ created ]

jobs:
  gpt_translate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run GPT Translate
        if: |
          contains(github.event.comment.body, '/gpt-translate') || 
          contains(github.event.comment.body, '/gt')
        uses: 3ru/gpt-translate@master
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: ${{ secrets.OPENAI_API_MODEL }} #gpt-4o-mini
```

### How do you run translations?

By Commit

**Comment by 3ru** [comment]
@zhgchgli0718 

Thank you for using! 
This is less of a bug and more about **needing to provide stricter prompt** instructions to ensure the model preserves the original image paths during translation.
You can modify your workflow file to include a custom prompt that explicitly instructs the model to keep image links unchanged:

```yml
...
        with:
          apikey: ${{ secrets.OPENAI_API_KEY }}
          model: ${{ secrets.OPENAI_API_MODEL }} #gpt-4o-mini
          prompt: "Please translate the given text into naturalistic {targetLanguage}. Important: Do NOT modify any image markdown syntax or URLs. Keep all image references exactly as they appear in the original text, including paths like '![image title](/assets/mycat.png)'. Only translate the image title text if needed, but preserve the exact formatting and path."
```

This explicit prompt should help ensure the model preserves your image paths exactly as they appear in the original text. 
If you're still experiencing issues, you might need to experiment with different prompt variations to find what works best for your specific case.
